## Kconfig-like configuration sourcing

include $(CONFIG_FILE).dist
-include $(CONFIG_FILE)

ALL_TARGETS_y :=
ALL_TARGETS_m :=
ALL_TARGETS_n :=
ALL_TARGETS_$(CONFIG_CSS) += affresco_css
ALL_TARGETS_$(CONFIG_RUN_JSHINT) += run_jshint
ALL_TARGETS_$(CONFIG_JS) += affresco_js
ALL_TARGETS := $(ALL_TARGETS_y) $(ALL_TARGETS_m)


JS_TARGETS_y :=
JS_TARGETS_n :=
JS_TARGETS_m :=
JS_TARGETS_$(CONFIG_JS_AFFIX) += js/bootstrap-affix.js
JS_TARGETS_$(CONFIG_JS_ALERT) += js/bootstrap-alert.js
JS_TARGETS_$(CONFIG_JS_BUTTON) += js/bootstrap-button.js
JS_TARGETS_$(CONFIG_JS_CAROUSEL) += js/bootstrap-carousel.js
JS_TARGETS_$(CONFIG_JS_COLLAPSE) += js/bootstrap-collapse.js
JS_TARGETS_$(CONFIG_JS_DROPDOWN) += js/bootstrap-dropdown.js
JS_TARGETS_$(CONFIG_JS_MODAL) += js/bootstrap-modal.js
JS_TARGETS_$(CONFIG_JS_POPOVER) += js/bootstrap-popover.js
JS_TARGETS_$(CONFIG_JS_SCROLLSPY) += js/bootstrap-scrollspy.js
JS_TARGETS_$(CONFIG_JS_TAB) += js/bootstrap-tab.js
JS_TARGETS_$(CONFIG_JS_TOOLTIP) += js/bootstrap-tooltip.js
JS_TARGETS_$(CONFIG_JS_TRANSITION) += js/bootstrap-transition.js
JS_TARGETS_$(CONFIG_JS_TYPEAHEAD) += js/bootstrap-typeahead.js

AFFRESCO_JS_SOURCES := $(JS_TARGETS_y)
AFFRESCO_JS_FILES = $(patsubst js/%.js,$(BUILD_DIR)/js/%.js,$(JS_TARGETS_m))


CSS_TARGETS_AFFRESCO_y :=
CSS_TARGETS_AFFRESCO_n :=
CSS_TARGETS_AFFRESCO_m :=

#CSS_TARGETS_AFFRESCO_$(CONFIG_CSS_VARIABLES) += scss/variables.scss
#CSS_TARGETS_AFFRESCO_$(CONFIG_CSS_MIXINS) += scss/mixins.scss

CSS_TARGETS_AFFRESCO_$(CONFIG_CSS_ACCORDION) += scss/accordion.scss
CSS_TARGETS_AFFRESCO_$(CONFIG_CSS_ALERTS) += scss/alerts.scss
CSS_TARGETS_AFFRESCO_$(CONFIG_CSS_BREADCRUMBS) += scss/breadcrumbs.scss
CSS_TARGETS_AFFRESCO_$(CONFIG_CSS_BUTTON_GROUPS) += scss/button-groups.scss
CSS_TARGETS_AFFRESCO_$(CONFIG_CSS_BUTTONS) += scss/buttons.scss
CSS_TARGETS_AFFRESCO_$(CONFIG_CSS_CAROUSEL) += scss/carousel.scss
CSS_TARGETS_AFFRESCO_$(CONFIG_CSS_CLOSE) += scss/close.scss
CSS_TARGETS_AFFRESCO_$(CONFIG_CSS_CODE) += scss/code.scss
CSS_TARGETS_AFFRESCO_$(CONFIG_CSS_COMPONENT_ANIMATIONS) += scss/component-animations.scss
CSS_TARGETS_AFFRESCO_$(CONFIG_CSS_DROPDOWNS) += scss/dropdowns.scss
CSS_TARGETS_AFFRESCO_$(CONFIG_CSS_FORMS) += scss/forms.scss
CSS_TARGETS_AFFRESCO_$(CONFIG_CSS_GRID) += scss/grid.scss
CSS_TARGETS_AFFRESCO_$(CONFIG_CSS_HERO_UNIT) += scss/hero-unit.scss
CSS_TARGETS_AFFRESCO_$(CONFIG_CSS_LABELS_BADGES) += scss/labels-badges.scss
CSS_TARGETS_AFFRESCO_$(CONFIG_CSS_LAYOUTS) += scss/layouts.scss
CSS_TARGETS_AFFRESCO_$(CONFIG_CSS_MEDIA) += scss/media.scss
CSS_TARGETS_AFFRESCO_$(CONFIG_CSS_MODALS) += scss/modals.scss
CSS_TARGETS_AFFRESCO_$(CONFIG_CSS_NAVBAR) += scss/navbar.scss
CSS_TARGETS_AFFRESCO_$(CONFIG_CSS_NAVS) += scss/navs.scss
CSS_TARGETS_AFFRESCO_$(CONFIG_CSS_PAGER) += scss/pager.scss
CSS_TARGETS_AFFRESCO_$(CONFIG_CSS_PAGINATION) += scss/pagination.scss
CSS_TARGETS_AFFRESCO_$(CONFIG_CSS_POPOVERS) += scss/popovers.scss
CSS_TARGETS_AFFRESCO_$(CONFIG_CSS_PROGRESS_BARS) += scss/progress-bars.scss
CSS_TARGETS_AFFRESCO_$(CONFIG_CSS_RESET) += scss/reset.scss
CSS_TARGETS_AFFRESCO_$(CONFIG_CSS_SCAFFOLDING) += scss/scaffolding.scss
#CSS_TARGETS_AFFRESCO_$(CONFIG_CSS_SPRITES) += scss/sprites.scss
CSS_TARGETS_AFFRESCO_$(CONFIG_CSS_TABLES) += scss/tables.scss
CSS_TARGETS_AFFRESCO_$(CONFIG_CSS_THUMBNAILS) += scss/thumbnails.scss
CSS_TARGETS_AFFRESCO_$(CONFIG_CSS_TOOLTIP) += scss/tooltip.scss
CSS_TARGETS_AFFRESCO_$(CONFIG_CSS_TYPE) += scss/type.scss
CSS_TARGETS_AFFRESCO_$(CONFIG_CSS_UTILITIES) += scss/utilities.scss
CSS_TARGETS_AFFRESCO_$(CONFIG_CSS_WELLS) += scss/wells.scss

AFFRESCO_CSS_SOURCES := $(CSS_TARGETS_AFFRESCO_y)
AFFRESCO_CSS_FILES := $(patsubst scss/%.scss,$(BUILD_DIR)/css/%.css,$(CSS_TARGETS_AFFRESCO_m))


CSS_TARGETS_AFFRESCO_RESPONSIVE_y :=
CSS_TARGETS_AFFRESCO_RESPONSIVE_n :=
CSS_TARGETS_AFFRESCO_RESPONSIVE_m :=

#CSS_TARGETS_AFFRESCO_RESPONSIVE_$(CONFIG_CSS_VARIABLES) += scss/variables.scss
#CSS_TARGETS_AFFRESCO_RESPONSIVE_$(CONFIG_CSS_MIXINS) += scss/mixins.scss

CSS_TARGETS_AFFRESCO_RESPONSIVE_$(CONFIG_CSS_RESPONSIVE_1200PX_MIN) += scss/responsive-1200px-min.scss
CSS_TARGETS_AFFRESCO_RESPONSIVE_$(CONFIG_CSS_RESPONSIVE_767PX_MAX) += scss/responsive-767px-max.scss
CSS_TARGETS_AFFRESCO_RESPONSIVE_$(CONFIG_CSS_RESPONSIVE_768PX_979PX) += scss/responsive-768px-979px.scss
CSS_TARGETS_AFFRESCO_RESPONSIVE_$(CONFIG_CSS_RESPONSIVE_NAVBAR) += scss/responsive-navbar.scss
CSS_TARGETS_AFFRESCO_RESPONSIVE_$(CONFIG_CSS_RESPONSIVE_UTILITIES) += scss/responsive-utilities.scss

AFFRESCO_RESPONSIVE_CSS_SOURCES := $(CSS_TARGETS_AFFRESCO_RESPONSIVE_y)
AFFRESCO_RESPONSIVE_CSS_FILES := $(patsubst scss/%.scss,$(BUILD_DIR)/css/%.css,$(CSS_TARGETS_AFFRESCO_RESPONSIVE_m))
